Algoritmo "Variaveis 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Toledo
// Data atual  : 5/14/2022
Var
// Seção de Declarações das variáveis 
   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo